BEGIN;

DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS orgs;
CREATE TABLE orgs (
	id INT4 NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
	name TEXT NOT NULL ,
	email TEXT NOT NULL 
);
CREATE TABLE users (
	id INT4 NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY UNIQUE,
	name TEXT NOT NULL ,
	email TEXT NOT NULL ,
	password TEXT NOT NULL ,
	login_count INT8 NOT NULL ,
	last_login TIMESTAMPTZ NOT NULL ,
	total_cost FLOAT8 NOT NULL ,
	org_id INT4 NOT NULL ,
	personal_org_id INT4 NOT NULL ,
	FOREIGN KEY (org_id) REFERENCES orgs(id),
	FOREIGN KEY (personal_org_id) REFERENCES orgs(id)
);

COMMIT;
