[package]
name = "repack"
description = "Powerful model codegen."
version = "0.1.0"
edition = "2024"
license = "GNU GPLv3"
repository = "https://github.com/jacksonzamorano/repack"
homepage = "https://github.com/jacksonzamorano/repack"
